development: &default
  adapter: postgresql
  database: grateful-because_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: grateful-because_test
